// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Hasher is an autogenerated mock type for the hasher type
type Hasher struct {
	mock.Mock
}

// GenerateShortLink provides a mock function with given fields: initialLink
func (_m *Hasher) GenerateShortLink(initialLink string) string {
	ret := _m.Called(initialLink)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(initialLink)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewHasher creates a new instance of Hasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hasher {
	mock := &Hasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
