// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RetrieverSender is an autogenerated mock type for the retrieverSender type
type RetrieverSender struct {
	mock.Mock
}

// CreateSlug provides a mock function with given fields: ctx, url, slug
func (_m *RetrieverSender) CreateSlug(ctx context.Context, url string, slug string) error {
	ret := _m.Called(ctx, url, slug)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, url, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetrieveURL provides a mock function with given fields: ctx, slug
func (_m *RetrieverSender) RetrieveURL(ctx context.Context, slug string) (string, error) {
	ret := _m.Called(ctx, slug)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRetrieverSender creates a new instance of RetrieverSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRetrieverSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *RetrieverSender {
	mock := &RetrieverSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
